services:
  cadvisor:
    image: ${REGISTRY:-}gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION:-latest}
    container_name: cadvisor
    # ports:
      # - "8080:8080"
    command:
      - "-port=8080"
      - "-listen_ip=0.0.0.0"
      - "-docker_only=true"
      - "-housekeeping_interval=10s"
      - "-store_container_labels=true"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first
    networks:
      - observability-network

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
