services:
  cadvisor:
    image: ${REGISTRY:-}ghcr.io/google/cadvisor:${CADVISOR_VERSION:-latest}
    container_name: cadvisor
    command:
      - "-port=8080"
      - "-docker_only"
    volumes:
      - /:/rootfs:ro,rslave
      - /sys:/sys:ro,rslave
      - /var/run:/var/run:ro,rslave
      - /var/lib/docker/:/var/lib/docker:ro,rslave
      - /dev/disk/:/dev/disk:ro,rslave
      - /cgroup:/cgroup:ro,rslave
    privileged: true # TODO: remove this if possible
    networks:
      - observability-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
