scrape_configs:
  - job_name: "k6"
    scrape_interval: 15s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:6565"

storage:
  tsdb:
    retention:
      time: 15d
