services:
  grafana:
    image: ${REGISTRY:-}grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: grafana
    ports:
      - "13000:3000"
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_ENABLE_GZIP=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-grafana}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-grafana}
      - GF_DASHBOARD_CLEAN_UP_INTERVAL=10s
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victoriametrics-metrics-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2G
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first
    networks:
      - observability-network

volumes:
  grafana-data:
    name: grafana-data
    driver: local

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
