services:
  prometheus:
    image: ${REGISTRY:-}prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus
    ports:
      - "19090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--config.auto-reload-interval=30s"
      - "--web.listen-address=:9090"
      - "--web.enable-otlp-receiver"
      - "--storage.tsdb.path=/prometheus/data"
      - "--log.format=json"
    volumes:
      - ./prometheus_cfg.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2G
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first
    networks:
      - monitoring-network

volumes:
  prometheus-data:
    name: prometheus-data
    driver: local

networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge
