# deprecated, prefer using victoria-metrics if possible
services:
  prometheus:
    image: ${REGISTRY:-}prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - "--web.listen-address=:9090"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-otlp-receiver"
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--config.auto-reload-interval=30s"
      - "--storage.tsdb.path=data/"
      - "--log.format=json"
    volumes:
      - x/prometheus_cfg.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    networks:
      - observability-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 6G

      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first

volumes:
  prometheus-data:
    name: prometheus-data
    driver: local

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
