services:
  victoria-metrics:
    image: ${REGISTRY:-}victoriametrics/victoria-metrics:${VICTORIA_METRICS_VERSION:-latest}
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    command:
      - "-httpListenAddr=:8428"
      - "-retentionPeriod=1"
      - "-promscrape.config=/etc/prometheus/prometheus.yaml"
      - "-storageDataPath=victoria-metrics-data"
      - "-enableMetadata"
      - "-loggerFormat=json"
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
      - ./x/prometheus_cfg.yaml:/etc/prometheus/prometheus.yaml:ro
    networks:
      - observability-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 6G

      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first

volumes:
  victoria-metrics-data:
    name: victoria-metrics-data
    driver: local

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
