scrape_configs:
  - job_name: "cadvisor"
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "cadvisor:8080"
  - job_name: "node-exporter"
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:9100"
