services:
  cassandra:
    image: ${REGISTRY:-}cassandra:${CASSANDRA_VERSION:-latest}
    container_name: cassandra
    ports:
      - "19042:9042"
      - "17199:7199"
      - "17000:7000"
      - "17001:7001"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 8G
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - cassandra-network

volumes:
  cassandra-data:
    name: cassandra-data
    driver: local

networks:
  cassandra-network:
    name: cassandra-network
    driver: bridge
    external: true
