# otel-collector/instrumented-application --(otlp-grpc/otlp-http)--> jaeger-collector
# --> storage-backend --> jaeger-query & ui

services:
  jaeger-collector:
    image: ${REGISTRY:+$REGISTRY/}jaegertracing/jaeger-collector:${JAEGER_VERSION:-latest}
    container_name: jaeger-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "14267:14267"
      - "14268:14268"
      - "9411:9411"
      - "14250:14250"
    environment:
      - SPAN_STORAGE_TYPE=${SPAN_STORAGE_TYPE:-memory}
    command:
      - "--sampling.strategies-file=/etc/jaeger/sampling_strategies.json"
      - "--sampling.strategies-reload-interval=1m"
    volumes:
      - "./sampling_strategies.json:/etc/jaeger/sampling_strategies.json:ro"
    networks:
      - jaeger-network
    restart: unless-stopped

  jaeger-query:
    image: ${REGISTRY:+$REGISTRY/}jaegertracing/jaeger-query:${JAEGER_VERSION:-latest}
    container_name: jaeger-query
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    environment:
      - SPAN_STORAGE_TYPE=${SPAN_STORAGE_TYPE:-memory}
    networks:
      - jaeger-network
    restart: unless-stopped

networks:
  jaeger-network:
    driver: bridge
