services:
  jaeger-collector:
    image: ${REGISTRY:-}jaegertracing/jaeger-collector:${JAEGER_VERSION:-latest}
    ports:
      - "4317:4317"
      - "4318:4318"
      - "14267:14267"
      - "14268:14268"
      - "9411:9411"
      - "14250:14250"
    environment:
      - SPAN_STORAGE_TYPE=memory
    command:
      - "--collector.otlp.enabled=true"
      - "--collector.tags=jaeger-collector=true"
      - "--sampling.strategies-file=/etc/jaeger/sampling_strategies.json"
      - "--sampling.strategies-reload-interval=1m"
    configs:
      - source: jaeger-sampling-strategies
        target: /etc/jaeger/sampling_strategies.json
    networks:
      - jaeger-network
    restart: unless-stopped

configs:
  jaeger-sampling-strategies:
    name: jaeger-sampling-strategies
    file: ./sampling_strategies.json

networks:
  jaeger-network:
    driver: overlay
