services:
  jaeger-query:
    image: ${REGISTRY:-}jaegertracing/jaeger-query:${JAEGER_VERSION:-latest}
    container_name: jaeger-query
    ports:
      - "26685:16685"
      - "26686:16686"
      - "26687:16687"
    environment:
      - SPAN_STORAGE_TYPE=cassandra
    command:
      - "--cassandra.servers=${CASSANDRA_SERVERS:-127.0.0.1}"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first
    networks:
      - observability-network

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
