services:
  jaeger-collector:
    image: ${REGISTRY:+$REGISTRY/}jaegertracing/jaeger-collector:${JAEGER_VERSION:-latest}
    container_name: jaeger-collector
    # command:
    ports:
      - "4317:4317"
      - "4318:4318"




