# otel-collector/instrumented-application --(otlp-grpc/otlp-http)--> jaeger-collector
# --> storage-backend --> jaeger-query & ui

services:
  jaeger-collector:
    image: ${REGISTRY:+$REGISTRY/}jaegertracing/jaeger-collector:${JAEGER_VERSION:-latest}
    container_name: jaeger-collector
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "14267:14267" # Remote Sampling & Jaeger Thrift over HTTP
      - "14268:14268" # Admin Health Check & Metrics HTTP
      - "9411:9411" # Zipkin
      - "14250:14250" # Jaeger gRPC
    environment:
      - SPAN_STORAGE_TYPE=memory
    networks:
      - jaeger-network
    restart: unless-stopped

  jaeger-query:
    image: ${REGISTRY:+$REGISTRY/}jaegertracing/jaeger-query:${JAEGER_VERSION:-latest}
    container_name: jaeger-query
    ports:
      - "16685:16685" # QueryService gRPC
      - "16686:16686" # Jaeger UI HTTP
      - "16687:16687" # Admin Health Check & Metrics HTTP
    networks:
      - jaeger-network
    restart: unless-stopped

networks:
  jaeger-network:
    driver: bridge
