services:
  jaeger-query:
    image: ${REGISTRY:-}jaegertracing/jaeger-query:${JAEGER_VERSION:-latest}
    container_name: jaeger-query
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    environment:
      - SPAN_STORAGE_TYPE=cassandra
    command:
      - "--cassandra.servers=${CASSANDRA_SERVERS:-host.docker.internal:9042}"
    networks:
      - observability-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
