services:
  jaeger-ingester:
    image: ${REGISTRY:-}jaegertracing/jaeger-ingester:${JAEGER_VERSION:-latest}
    container_name: jaeger-ingester
    ports:
      - "14270:14270"
    environment:
      - SPAN_STORAGE_TYPE=cassandra
    command:
      - "--kafka.consumer.brokers=${KAFKA_BROKERS:-host.docker.internal:9092}"
      - "--cassandra.servers=${CASSANDRA_SERVERS:-host.docker.internal:9042}"
    networks:
      - observability-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
